version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: advantissurgerydb
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/advantissurgerydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123

volumes:
  mysql-data:
